train_path: 'data/drugs_processed/train_data_39k.pkl'
rc_train_path: '../rdkit-clustering/output/drugs/train.lmdb'
val_path: 'data/drugs_processed/val_data_5k.pkl'
rc_val_path: '../rdkit-clustering/output/drugs/val.lmdb'
test_path: 'data/drugs_processed/test_data_200.pkl'
rc_test_path: '../rdkit-clustering/output/drugs/test.lmdb'

n_node_features: 74

from_torsion: false
from_rc: true
from_dmcg: false
add_coords: false

etkdg_noise: null
etkdg: false
uniform_ratio: null