train_path: 'data/drugs_processed/train_data_39k.pkl'
val_path: 'data/drugs_processed/val_data_5k.pkl'
test_path: 'data/drugs_processed/test_data_200.pkl'

n_node_features: 74
etkdg: false
etkdg_noise: null
etkdg_noise_random: false
zero_com: false

scale: null

removeH: false

from_torsion: false
from_rc: false
from_dmcg: false

uniform_ratio: null