train_path: 'data/qm9_processed/train_data_40k.pkl'
dmcg_train_path: '../dmcg/qm9/train.pkl'
val_path: 'data/qm9_processed/val_data_5k.pkl'
dmcg_val_path: '../dmcg/qm9/val.pkl'
test_path: 'data/qm9_processed/test_data_200.pkl'
dmcg_test_path: '../dmcg/qm9/test.pkl'

n_node_features: 44

from_torsion: false
from_rc: false
from_dmcg: true

etkdg_noise: null
etkdg: false
uniform_ratio: null