train_path: 'data/qm9_processed/train_data_40k.pkl'
rc_train_path: '../rdkit-clustering/output/qm9/train.lmdb'
val_path: 'data/qm9_processed/val_data_5k.pkl'
rc_val_path: '../rdkit-clustering/output/qm9/val.lmdb'
test_path: 'data/qm9_processed/test_data_200.pkl'
rc_test_path: '../rdkit-clustering/output/qm9/test.lmdb'

n_node_features: 44

from_torsion: false
from_rc: true
from_dmcg: false
add_coords: false

etkdg_noise: null
etkdg: false
uniform_ratio: null