defaults:
  - model: 'egnn'
  - diffusion: 'ddpm'
  - train: 'train-default'
  - dataset: 'drugs'
  - logger: 'wandb'
  - hydra: 'hydra-default'
  - _self_


seed: 42
name: 'egnn-ddpm-drugs'
gpu: 0
ckpt_path: ${hydra:run.dir}/ckpts/${name}.ckpt