noise_schedule:
  _target_: disco.diffusions.symmetric_sigmoid_schedule
  beta_start: 1e-7
  beta_end: 2e-3
  n_timesteps: 10

diffusion:
  _partial_: true
  _target_: disco.diffusions.I2SBDiffusion

