noise_schedule:
  _target_: src.diffusions.noise_schedule.sigmoid_schedule
  beta_start: 1e-7
  beta_end: 2e-3
  n_timesteps: 5000

diffusion:
  _partial_: true
  _target_: src.diffusions.ddpm.GaussianDiffusion
  posterior_var_type: 'beta'

