optimizer_type: 'adamw'

batch_size: 32
num_workers: 8
n_epochs: 100
lr: 1e-4
weight_decay: 1e-12
patience: 20
ema_decay: 0.999
grad_clip: 1000.0

n_test_samples: 200
test_batch_size: 64
test_interval: 20
return_traj: false
test_etkdg_noise: 0.0

prop_start: ours

test_starting_point: false

test_mmff: false
test_mmff_iters: 1000